<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNNEH38U\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNNEH38U/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerNNEH38U.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerNNEH38U\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerNNEH38U\App_KernelProdContainer([
    'container.build_hash' => 'NNEH38U',
    'container.build_id' => '4314335b',
    'container.build_time' => 1627485274,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNNEH38U');
